name: Deploy Rock Paper Scissors Game

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - run: npm install

      # Compile TypeScript
      - run: npx tsc

      # Prepare deployment folder (dist + other assets)
      - name: Prepare Deployment
        run: |
          mkdir deploy
          cp -r dist/* deploy/
          cp index.html deploy/
          cp stylegame.css deploy/
          cp -r images deploy/
          cp -r Music deploy/

      # Deploy to GitHub Pages
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master        # branch to deploy to
          folder: deploy         # folder to deploy
          clean: true
